// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHHz1A8tWCioosQp9jcsy1TJAqAFbn1E',
    appId: '1:815429673377:web:9e738884bbf9a280e0abe0',
    messagingSenderId: '815429673377',
    projectId: 'chatapp-31b11',
    authDomain: 'chatapp-31b11.firebaseapp.com',
    storageBucket: 'chatapp-31b11.appspot.com',
    measurementId: 'G-3FXF8EGNGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9x8PiUjVNV4gASq3t3h_EvFOgoV8s9g',
    appId: '1:815429673377:android:5f9df59f2daa3e6be0abe0',
    messagingSenderId: '815429673377',
    projectId: 'chatapp-31b11',
    storageBucket: 'chatapp-31b11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1RaUw_Ngint47J5laRRPwdyVXc68sIOs',
    appId: '1:815429673377:ios:5827b027ccea4af9e0abe0',
    messagingSenderId: '815429673377',
    projectId: 'chatapp-31b11',
    storageBucket: 'chatapp-31b11.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1RaUw_Ngint47J5laRRPwdyVXc68sIOs',
    appId: '1:815429673377:ios:5827b027ccea4af9e0abe0',
    messagingSenderId: '815429673377',
    projectId: 'chatapp-31b11',
    storageBucket: 'chatapp-31b11.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcHHz1A8tWCioosQp9jcsy1TJAqAFbn1E',
    appId: '1:815429673377:web:4e7cffbb9b903933e0abe0',
    messagingSenderId: '815429673377',
    projectId: 'chatapp-31b11',
    authDomain: 'chatapp-31b11.firebaseapp.com',
    storageBucket: 'chatapp-31b11.appspot.com',
    measurementId: 'G-1689VLBTGW',
  );

}